# Generated by Django 3.2.9 on 2021-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mapel', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], default='C1', max_length=2)),
            ],
        ),
    ]
