# Generated by Django 3.2.9 on 2021-11-18 14:16

from django.db import migrations, models
import parent_center_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='id',
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default=parent_center_app.utils.custom_mapel, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
