# Generated by Django 3.2.9 on 2021-11-18 15:13

from django.db import migrations, models
import parent_center_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0002_auto_20211118_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.CharField(default='adm-18112021221344704834', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('no_tlp', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default=parent_center_app.utils.custom_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
