# Generated by Django 3.2.9 on 2021-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0004_auto_20211118_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.CharField(default='kls-18112021223804400808', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('kelas', models.CharField(choices=[('Teknik Intalasi Tenaga Listrik', 'Titl'), ('Teknik Pemesinan', 'Tp'), ('Teknik Kendaraan Ringan', 'Tkr'), ('Teknik Komputer Jaringan', 'Tkj'), ('Rekayasa Perangkat Lunak', 'Rpl'), ('Teknik dan Bisnis Sepeda Motor', 'Tbsm')], default='Teknik Intalasi Tenaga Listrik', max_length=30)),
                ('no_kelas', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-18112021223804400808', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-18112021223804400808', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
