# Generated by Django 3.2.9 on 2021-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0005_auto_20211118_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.CharField(choices=[('Teknik Intalasi Tenaga Listrik', 'Titl'), ('Teknik Pemesinan', 'Tp'), ('Teknik Kendaraan Ringan', 'Tkr'), ('Teknik Komputer Jaringan', 'Tkj'), ('Rekayasa Perangkat Lunak', 'Rpl'), ('Teknik dan Bisnis Sepeda Motor', 'Tbsm')], default='Teknik Intalasi Tenaga Listrik', max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-18112021223919851318', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-18112021223919851318', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='kelas',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'Xi'), ('XII', 'Xii')], default='X', max_length=3),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-18112021223919851318', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
