# Generated by Django 3.2.9 on 2021-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0006_auto_20211118_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id_guru', models.CharField(default='gru-18112021233252930450', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('no_tlp', models.CharField(max_length=12)),
                ('no_induk', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-18112021233252930450', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-18112021233252930450', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-18112021233252930450', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
