# Generated by Django 3.2.9 on 2021-11-18 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0007_auto_20211118_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-19112021012038507647', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default='gru-19112021012038507647', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-19112021012038507647', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-19112021012038507647', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.guru')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.mapel')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id_siswa', models.CharField(default='sis-19112021012038507647', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('tpt_lahir', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateTimeField(default=datetime.datetime.now)),
                ('agama', models.CharField(max_length=15)),
                ('jns_kelamin', models.CharField(choices=[('Perempuan', 'P'), ('Laki-Laki', 'L')], default='Laki-Laki', max_length=10)),
                ('id_kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.kelas')),
            ],
        ),
    ]
