# Generated by Django 3.2.9 on 2021-11-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0010_auto_20211119_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='id_kelas',
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-19112021012641585277', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default='gru-19112021012641585277', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-19112021012641585277', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-19112021012641585277', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='id_siswa',
            field=models.CharField(default='sis-19112021012641585277', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
