# Generated by Django 3.2.9 on 2021-11-18 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0012_auto_20211119_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-19112021013246804467', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default='gru-19112021013246805467', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-19112021013246802467', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-19112021013246796472', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='id_siswa',
            field=models.CharField(default='sis-19112021013246807466', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tgl_lahir',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
