# Generated by Django 3.2.9 on 2021-11-19 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0013_auto_20211119_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id_absen', models.CharField(default='abs-19112021214636015204', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('tgl', models.DateField(default=datetime.date.today)),
                ('pertemuan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(default='usr-19112021214635999581', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('user_level', models.CharField(choices=[('Admin', 'Admin'), ('Guru', 'Guru'), ('OrangTua', 'Ortu')], default='Guru', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tugas',
            name='id',
        ),
        migrations.AddField(
            model_name='admin',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='no_tlp',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tugas',
            name='id_tugas',
            field=models.CharField(default='tgs-19112021214635999581', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-19112021214635999581', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default='gru-19112021214635999581', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-19112021214635999581', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-19112021214635999581', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='id_siswa',
            field=models.CharField(default='sis-19112021214635999581', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='id_guru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.guru'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='keterangan',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=50)),
                ('no_tlp', models.CharField(max_length=13)),
                ('alamat', models.TextField(null=True)),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.siswa')),
                ('id_tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.tugas')),
            ],
        ),
        migrations.CreateModel(
            name='DaftarAbsen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(choices=[('Hadir', 'H'), ('Alfa', 'A'), ('Izin', 'I'), ('Sakit', 'S')], default='Hadir', max_length=10)),
                ('id_absen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.absen')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.siswa')),
            ],
        ),
        migrations.AddField(
            model_name='absen',
            name='id_guru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.guru'),
        ),
        migrations.AddField(
            model_name='absen',
            name='id_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.kelas'),
        ),
        migrations.AddField(
            model_name='absen',
            name='id_mapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.mapel'),
        ),
    ]
