# Generated by Django 3.2.9 on 2021-11-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0015_auto_20211119_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.user'),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.user'),
        ),
        migrations.AlterField(
            model_name='absen',
            name='id_absen',
            field=models.CharField(default='abs-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default='adm-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default='gru-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default='kls-19112021214748976085', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default='mpl-19112021214748976085', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='id_siswa',
            field=models.CharField(default='sis-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='id_tugas',
            field=models.CharField(default='tgs-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(default='usr-19112021214748976085', editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
