# Generated by Django 3.2.9 on 2021-11-21 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parent_center_app.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent_center_app', '0017_auto_20211119_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='jns_kelamin',
            field=models.CharField(choices=[('Perempuan', 'P'), ('Laki-Laki', 'L')], default='Laki-Laki', max_length=10),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='absen',
            name='id_absen',
            field=models.CharField(default=parent_center_app.utils.custom_absen, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.CharField(default=parent_center_app.utils.custom_adm, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_guru',
            field=models.CharField(default=parent_center_app.utils.custom_guru, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(default=parent_center_app.utils.custom_kelas, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='id_mapel',
            field=models.CharField(default=parent_center_app.utils.custom_mapel, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pembayaranspp',
            name='id_pembayaran',
            field=models.CharField(default=parent_center_app.utils.custom_spp, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='id_siswa',
            field=models.CharField(default=parent_center_app.utils.custom_siswa, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='id_tugas',
            field=models.CharField(default=parent_center_app.utils.custom_tugas, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.CharField(default=parent_center_app.utils.custom_jadwal, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat')], default='Senin', max_length=10)),
                ('jumlah_jam', models.IntegerField()),
                ('mapel_ke', models.IntegerField()),
                ('id_guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.guru')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_center_app.mapel')),
            ],
        ),
        migrations.CreateModel(
            name='Extend_User',
            fields=[
                ('id_user', models.CharField(default=parent_center_app.utils.custom_user, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_level', models.CharField(choices=[('Admin', 'Admin'), ('Guru', 'Guru'), ('Orang Tua', 'Ortu')], default='Guru', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
        migrations.AlterField(
            model_name='orangtua',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
