# Generated by Django 3.2.9 on 2021-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0018_auto_20211121_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='jenis',
            field=models.CharField(choices=[('Muatan Nasional', 'A'), ('Muatan Kewilayahan', 'B'), ('Muatan Peminatan Kejuruan', 'C1'), ('Dasar Program Keahlian', 'C2'), ('Kompetensi Keahlian', 'C3')], default='Muatan Peminatan Kejuruan', max_length=30),
        ),
    ]
