# Generated by Django 3.2.9 on 2021-11-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0019_alter_mapel_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
        migrations.AlterField(
            model_name='orangtua',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent_center_app.extend_user'),
        ),
    ]
