# Generated by Django 3.2.9 on 2021-12-06 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent_center_app', '0020_auto_20211123_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extend_User',
            new_name='ExtendUser',
        ),
        migrations.AddField(
            model_name='orangtua',
            name='jns_kelamin',
            field=models.CharField(choices=[('Perempuan', 'P'), ('Laki-Laki', 'L')], default='Laki-Laki', max_length=10),
        ),
    ]
