# Generated by Django 3.2.9 on 2021-12-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0021_auto_20211206_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='mapel_ke',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='mulai',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='selesai',
            field=models.TimeField(null=True),
        ),
    ]
