# Generated by Django 3.2.9 on 2021-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0022_auto_20211206_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='jenis',
            field=models.CharField(choices=[('A', 'A. Muatan Nasional'), ('B', 'B. Muatan Kewilayahan'), ('C1', 'C1. Muatan Peminatan Kejuruan'), ('C2', 'C2. Dasar Program Keahlian'), ('C3', 'C3. Kompetensi Keahlian')], default='A', max_length=30),
        ),
    ]
