# Generated by Django 3.2.9 on 2021-12-20 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0023_alter_mapel_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaranspp',
            name='bulan_ke',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pembayaranspp',
            name='jumlah',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pembayaranspp',
            name='semester',
            field=models.CharField(choices=[('1', 'Ganjil'), ('2', 'Genap')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='pembayaranspp',
            name='thn_ajar',
            field=models.CharField(max_length=5),
        ),
    ]
