# Generated by Django 3.2.9 on 2021-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_center_app', '0026_alter_pembayaranspp_thn_ajar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarabsen',
            name='keterangan',
            field=models.CharField(choices=[('H', 'Hadir'), ('A', 'Alfa'), ('I', 'Izin'), ('S', 'Sakit')], default='H', max_length=10),
        ),
    ]
